---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-2048
  labels:
    app: game-2048
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-2048
  template:
    metadata:
      labels:
        app: game-2048
    spec:
      containers:
        - image: alexwhen/docker-2048:latest # New-Test
          name: game-2048
          ports:
            - name: web
              containerPort: 80
